#include <stdio.h>
#include <unistd.h>
int main(void) {
  printf("minimum number of standard I/O streams that the implementation "
         "gurantees can be open at once: %d\n"
         "STREAM_MAX has the same value: %ld\n",
         FOPEN_MAX, sysconf(_SC_STREAM_MAX));

  printf("the maximum number of unique filenames generated by the tmpnam function: %d\n", TMP_MAX);

  printf("max filename: %d\n", FILENAME_MAX);

  
}